### ISSUE TITLE
Crom support for Backrooms Branches

### ISSUE THREAD

**Issue by wolf20482** [croque-scp/notifier#49]
Since Crom support for Backrooms branches has gone out of beta and in stable phase, the Crom field of "backrooms-wiki" wiki in the Supported Wikis wiki page should be ticked and Crom should be used on that wiki

**Comment by rossjrw** [comment]
Noted, thank you! I've ticked the box on the wiki config.

The notifier doesn't currently use Crom, though I plan to do so in future, which is why I've got that checkbox on each of the configs. When I eventually get around to adding that feature, I'll be sure to include the Backrooms.

If the other (non-English) Backrooms branches wish to have forum notifications enabled, they should get in touch with me.
